### ISSUE TITLE
Needs a usage information flag.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/report#1]
This useful tool needs to spit out helpful usage information. What are the flags and order.

```
$ java -jar <jar-file> --help
Exception in thread "main" java.lang.RuntimeException: org.aesh.command.parser.OptionParserException: The option --help is unknown.
	at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:182)
	at org.aesh.AeshRuntimeRunner.execute(AeshRuntimeRunner.java:98)
	at io.hyperfoil.report.ReportGenerator.main(ReportGenerator.java:116)
Caused by: org.aesh.command.parser.OptionParserException: The option --help is unknown.
	at org.aesh.command.impl.parser.AeshCommandLineParser.doParse(AeshCommandLineParser.java:339)
	at org.aesh.command.impl.parser.AeshCommandLineParser.parse(AeshCommandLineParser.java:297)
	at org.aesh.command.container.DefaultCommandContainer.parseAndPopulate(DefaultCommandContainer.java:70)
	at org.aesh.command.impl.Executions$ExecutionImpl.populateCommand(Executions.java:113)
	at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:127)
	at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:161)
	... 2 more
$
```

**Comment by rvansa** [comment]
Out of date.
