### ISSUE TITLE
j.l.NullPointerException running the reporter.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/report#2]
When running the report tool I am getting a NullPointerException.

```
$ /usr/lib/jvm/java-11-openjdk/bin/java -jar ../Hyperfoil-report/target/report-0.1-SNAPSHOT-jar-with-dependencies.jar -s  /tmp/hyperfoil/workspace/run/00C1/ -d /tmp/hyperfoil/workspace/run/00C1/index.html
ignored:
  /tmp/hyperfoil/workspace/run/00C1/3scale-benchmark.serialized
  /tmp/hyperfoil/workspace/run/00C1/3scale-benchmark.yaml
  /tmp/hyperfoil/workspace/run/00C1/stats/all.json
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:182)
	at org.aesh.AeshRuntimeRunner.execute(AeshRuntimeRunner.java:98)
	at io.hyperfoil.report.ReportGenerator.main(ReportGenerator.java:116)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:200)
	at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:161)
	... 2 more
Caused by: java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at io.hyperfoil.report.ReportGenerator.execute(ReportGenerator.java:173)
	at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
	at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:177)
	... 3 more

```

**Comment by whitingjr** [comment]
When I check the contents of both jar files (snapshot, snapshot with dependencies) I do not find index.html file in the archive.

```
$ /usr/lib/jvm/java-11-openjdk/bin/jar -tf ../Hyperfoil-report/target/report-0.1-SNAPSHOT.jar |grep -c index
0
$ /usr/lib/jvm/java-11-openjdk/bin/jar -tf ../Hyperfoil-report/target/report-0.1-SNAPSHOT-jar-with-dependencies.jar |grep -c "index.html"
0
$

```

**Comment by whitingjr** [comment]
The solution has been found.
 The  reported issue is only seen when the number of times maven package goal is less than 2. The solution is to run maven package goal a second time.
 On my system doing a diff on the file structure showed the following differences.

```
$ diff /tmp/report-tree-01.txt /tmp/report-tree-02.txt 
18c18
< │       │   │   ├── precache-manifest.c1e59f1f6f2d3108dfa3b4b3a726f745.js
---
> │       │   │   ├── precache-manifest.05d4bbb68419d5f5bbd5a22c42a3e0b5.js
27,28c27,28
< │       │   │       │   ├── 2.96c514ed.chunk.js
< │       │   │       │   ├── 2.96c514ed.chunk.js.map
---
> │       │   │       │   ├── 2.f0aa9191.chunk.js
> │       │   │       │   ├── 2.f0aa9191.chunk.js.map
119831a119832,119836
>     │   ├── build
>     │   │   └── static
>     │   │       └── js
>     │   │           └── bundle.js.min.js
>     │   ├── index.html
119866c119871
< 6357 directories, 113506 files
---
> 6360 directories, 113508 files
$
```
 The cause of index.html not being bundled is the jar artifact I don't know. But the workaround is simple.

**Comment by rvansa** [comment]
Out of date.
