### ISSUE TITLE
NullPointerException running reporter.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/report#6]
Seeing a NullPointerException using a multi agent driver configuration.

>  /usr/lib/jvm/java-11-openjdk/bin/java -jar /home/benchuser/code/Hyperfoil-report/target/report-0.1-SNAPSHOT-jar-with-dependencies.jar -s /tmp/hyperfoil/workspace/run/01B1 -d /tmp/hyperfoil/workspace/run/01B1/index.html
> FOUND /tmp/hyperfoil/workspace/run/01B1/all.json
> Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
> 	at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:182)
> 	at org.aesh.AeshRuntimeRunner.execute(AeshRuntimeRunner.java:98)
> 	at io.hyperfoil.report.ReportGenerator.main(ReportGenerator.java:45)
> Caused by: java.lang.RuntimeException: java.lang.NullPointerException
> 	at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:200)
> 	at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:161)
> 	... 2 more
> Caused by: java.lang.NullPointerException
> 	at io.hyperfoil.report.ReportGenerator.execute(ReportGenerator.java:93)
> 	at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
> 	at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:177)
> 	... 3 more
> $
>

**Comment by whitingjr** [comment]
Only about communication with the 2nd agent.

**Comment by whitingjr** [comment]
This issue is no longer happening with 0.6 version of hyperfoil.
